Repository uprm-inso4117-2024-2025-s2/semester-project-thriftuni, pull requests merged in 2025-03, with the labels that each got.

#107 60 design the logout feature
  .idea/inspectionProfiles/profiles_settings.xml
  .idea/misc.xml
  .idea/shelf/Uncommitted_changes_before_Checkout_at_2_19_2025_11_58_PM_[Changes]/shelved.patch
  .idea/shelf/Uncommitted_changes_before_Checkout_at_2_19_2025_11_58_PM__Changes_.xml
  .idea/shelf/Uncommitted_changes_before_Update_at_3_6_2025_4_29_PM_[Changes]/shelved.patch
  .idea/shelf/Uncommitted_changes_before_Update_at_3_6_2025_4_29_PM__Changes_.xml
  .idea/vcs.xml
  .idea/workspace.xml
  ThriftUni/app/profile.tsx
  ThriftUni/components/LogoutButton.tsx
  ThriftUni/firebaseConfig.js
  ThriftUni/key.env
  ThriftUni/utils/logout.ts
Labels: Sign-up and Login Team

#128 Developed individual listing page.
  ThriftUni/app/(tabs)/index.tsx
  ThriftUni/app/_layout.tsx
  ThriftUni/app/listings/[id].tsx
  ThriftUni/components/DisplayIndividualListing.tsx
  ThriftUni/components/ImageCarousel.tsx
  ThriftUni/components/ListingDescription.tsx
  ThriftUni/components/ListingsPage/ProductCard.tsx
  ThriftUni/components/LocationMap.tsx
  ThriftUni/components/ProductImages.tsx
  ThriftUni/components/SellerCard.tsx
  ThriftUni/package-lock.json
  ThriftUni/yarn.lock
Labels: Milestone 2, Listings and Search team, Completed

#140 Implemented unit tests for the ProductCard and FiterMenu
  ThriftUni/components/ListingsPage/CategoryDropdown.tsx
  ThriftUni/components/ListingsPage/FilterMenu.tsx
  ThriftUni/components/__tests__/FilterMenu-test.tsx
  ThriftUni/components/__tests__/ProductCard-test.ts
  ThriftUni/components/__tests__/__snapshots__/StyledText-test.js.snap
  ThriftUni/package-lock.json
  ThriftUni/package.json
Labels: bug, Milestone 2, Listings and Search team

#147 Created Firestore Collections for Categories
  ThriftUni/app/(tabs)/_layout.tsx
  ThriftUni/db-setup.tsx
Labels: Milestone 2, Listings and Search team, Completed

#148 Added functionality to the buttons on the My Listing page.
  ThriftUni/app/(tabs)/my_listings.tsx
Labels: Milestone 2, Listings and Search team, Completed

#149 Implement Firestore security rules & unit tests
  ThriftUni/firestore-test.js
  ThriftUni/package-lock.json
  ThriftUni/package.json
  ThriftUni/yarn.lock
Labels: bug, Milestone 2, Sign-up and Login Team, Completed

#170 made WishlistPage ready for firebase once its done
  ThriftUni/app/(tabs)/WishlistPage.tsx
Labels: Listings and Search team, Completed

#150 Interests and sizes page
  ThriftUni/app/(tabs)/Profile.tsx
  ThriftUni/app/(tabs)/interestsandsizes.tsx
  ThriftUni/app/(tabs)/settings.tsx
  ThriftUni/package.json
  ThriftUni/tsconfig.json
  ThriftUni/yarn.lock
Labels: enhancement, Milestone 2, User Systems Team, Completed

#171 incomplete button connection implementation
  ThriftUni/app/(tabs)/listings.tsx
  ThriftUni/components/ListingsPage/FilterMenu.tsx
  ThriftUni/package-lock.json
  ThriftUni/package.json
  ThriftUni/yarn.lock
Labels: Milestone 2, Listings and Search team, TL Approved, Completed

#172 Revert "incomplete button connection implementation"
  ThriftUni/app/(tabs)/listings.tsx
  ThriftUni/components/ListingsPage/FilterMenu.tsx
  ThriftUni/package-lock.json
  ThriftUni/package.json
  ThriftUni/yarn.lock
Labels: Listings and Search team

#169 Implement login screen #114
  .gitignore
  ThriftUni/.gitignore
  ThriftUni/app/(tabs)/login.tsx
  ThriftUni/app/(tabs)/signup.tsx
  ThriftUni/components/ListingDescription.tsx
Labels: Milestone 2, Sign-up and Login Team, Completed

#197 135 set up database table for listing images
  ThriftUni/app/(tabs)/_layout.tsx
  ThriftUni/db-setup.tsx
Labels: Milestone 2, Listings and Search team

#183 Fixed imports and other changes that were not supposed to be made.
  ThriftUni/components/ListingDescription.tsx
Labels: Listings and Search team, TL Approved

#209 Main page, my listings and lecture topic task completion
  ThriftUni/app/(tabs)/main_page.tsx
  ThriftUni/components/ListingDescription.tsx
  ThriftUni/components/__tests__/ListingsTesting.tsx
  ThriftUni/documentation/my_listings.md
  ThriftUni/package-lock.json
  ThriftUni/package.json
Labels: Milestone 2, Listings and Search team, TL Approved, Completed

#208 Forgot password branch
  ThriftUni/app/(tabs)/settings.tsx
  ThriftUni/app/login/__tests__/ForgotPass.test.js
  ThriftUni/app/login/__tests__/Signup.test.js
  ThriftUni/app/login/forgot.tsx
  ThriftUni/app/login/login.tsx
  ThriftUni/app/login/signup.tsx
  ThriftUni/firebase/firebase.config.tsx
Labels: Milestone 2, Sign-up and Login Team, Completed

#210 Setup GitHub actions for tests
  .github/workflows/tests.yml
  .gitignore
  ThriftUni/.firebaserc
  ThriftUni/firebase.json
  ThriftUni/firestore-debug.log
  ThriftUni/firestore-test.js
  ThriftUni/firestore.indexes.json
  ThriftUni/firestore.rules
  ThriftUni/package-lock.json
  ThriftUni/package.json
  ThriftUni/yarn.lock
Labels: Milestone 2, Pending Approval, Sign-up and Login Team

#221 202 tdd unit tests for listing categories collection relations and behaviors
  ThriftUni/categories-test.js
Labels: Milestone 2, Listings and Search team, Completed

#224 Created Unit Tests for listing_images behavior
  ThriftUni/listing_images-test.js
Labels: Milestone 2, Listings and Search team, Completed

#225 Protected routes
  ThriftUni/app/(tabs)/Profile.tsx
  ThriftUni/app/(tabs)/WishlistPage.tsx
  ThriftUni/app/(tabs)/interestsandsizes.tsx
  ThriftUni/app/(tabs)/my_listings.tsx
  ThriftUni/app/(tabs)/settings.tsx
  ThriftUni/app/login/login.tsx
  ThriftUni/components/ProtectedRoute.tsx
  ThriftUni/firebase/firebase.config.tsx
  ThriftUni/firebaseConfig.js
Labels: Milestone 2, Pending Approval

#205 [Lecture Topic Task] Debugging and Test Preparation in Tab Navigation (_layout.tsx)
  .gitignore
  ThriftUni/app/(tabs)/_layout.tsx
  ThriftUni/app/(tabs)/index.tsx
  ThriftUni/app/login/__tests__/LoginScreen.test.js
  ThriftUni/app/login/login.tsx
  ThriftUni/components/ListingsPage/FilterMenu.tsx
  ThriftUni/components/__tests__/WishlistPageTest/Wishlist-test.tsx
  ThriftUni/constants/Colors.ts
  ThriftUni/firestore-test.js
  ThriftUni/package-lock.json
  ThriftUni/package.json
  ThriftUni/yarn.lock
Labels: enhancement, Milestone 2, Completed

#219 UI tests for login screen
  ThriftUni/app/login/__tests__/LoginScreen.test.js
  ThriftUni/app/login/login.tsx
  ThriftUni/components/__tests__/WishlistPageTest/Wishlist-test.tsx
  ThriftUni/package-lock.json
  ThriftUni/package.json
  ThriftUni/yarn.lock
Labels: Milestone 2, Completed
