Repository uprm-inso4117-2024-2025-s2/semester-project-thriftuni, pull requests merged in 2025-02, with the labels that each got.

#33 Add Firebase configuration and initialization with .env file
  ThriftUni/.env.exaple
  ThriftUni/.gitignore
  ThriftUni/app.json
  ThriftUni/app/(tabs)/index.tsx
  ThriftUni/firebase.config.tsx
  ThriftUni/package.json
  ThriftUni/yarn.lock
Labels: Milestone 1, Sign-up and Login Team, TL Approved, Completed

#97 firebase fix and profile page integration
  .vscode/settings.json
  ThriftUni/.env.exaple
  ThriftUni/app/(tabs)/Profile.tsx
  ThriftUni/firebase.config.tsx
  ThriftUni/firebaseConfig.js
  ThriftUni/yarn.lock
Labels: Milestone 1, Pending Approval, User Systems Team, Completed

#105 Sign Up page implementation and firebase connect
  ThriftUni/app/(tabs)/signup.tsx
Labels: Milestone 1, Sign-up and Login Team, Completed

#102 implement firebase authentication login function
  .gitignore
  ThriftUni/.gitignore
  ThriftUni/firebase/login.tsx
  ThriftUni/package.json
Labels: Milestone 1, Pending Approval, Sign-up and Login Team, TL Approved

#103 Settings Page Implementation Done
  ThriftUni/app/(tabs)/_layout.tsx
  ThriftUni/app/(tabs)/index.tsx
  ThriftUni/app/(tabs)/listings.tsx
  ThriftUni/app/(tabs)/settings.tsx
  ThriftUni/app/(tabs)/two.tsx
  ThriftUni/app/+not-found.tsx
  ThriftUni/components/ListingsPage/FilterMenu.tsx
  ThriftUni/package.json
  ThriftUni/yarn.lock
Labels: enhancement, Milestone 1, User Systems Team, Completed

#109 Implemented My Listing Page.
  ThriftUni/app/(tabs)/_layout.tsx
  ThriftUni/app/(tabs)/my_listings.tsx
  ThriftUni/package.json
Labels: Milestone 1, Pending Approval, Listings and Search team, TL Approved, Completed

#110 Fix: Added button to list an item.
  ThriftUni/app/(tabs)/ListItem.tsx
  ThriftUni/app/(tabs)/_layout.tsx
  ThriftUni/app/(tabs)/index.tsx
Labels: Milestone 1, Listings and Search team, TL Approved, Completed

#108 Wishlist
  ThriftUni/app/(tabs)/WishlistPage.tsx
  ThriftUni/app/(tabs)/_layout.tsx
  ThriftUni/assets/images/blanket.png
  ThriftUni/assets/images/bowl.png
  ThriftUni/assets/images/jewelry.png
  ThriftUni/assets/images/lamp.png
  ThriftUni/components/Wishlist/WishlistFilter.tsx
  ThriftUni/components/Wishlist/WishlistHeader.tsx
  ThriftUni/components/Wishlist/WishlistItem.tsx
Labels: Milestone 1, Listings and Search team, TL Approved, Completed

#104 Adding initial main page implementation to ThriftUni
  ThriftUni/app/(tabs)/main_page.tsx
  ThriftUni/documentation/main_page.md
  ThriftUni/package-lock.json
  ThriftUni/package.json
  ThriftUni/yarn.lock
Labels: Milestone 1, Pending Approval, Listings and Search team, TL Approved, Completed

#111 Authentification Implementation
  ThriftUni/app/(tabs)/_layout.tsx
  ThriftUni/app/(tabs)/authentication.tsx
  ThriftUni/app/(tabs)/index.tsx
Labels: Completed
