Repository uprm-inso4117-2024-2025-s2/semester-project-thriftuni, pull requests merged in 2025-04, with the labels that each got.

#251 Add Edit Modal, Mock Backend Integration, and Unit Tests for My Listing Page
  ThriftUni/app/(tabs)/my_listings.tsx
  ThriftUni/components/__tests__/DisplayMyListing.test.tsx
  ThriftUni/mock_backend/listingsData.json
  ThriftUni/mock_backend/mockApi.ts
  ThriftUni/package-lock.json
  ThriftUni/package.json
Labels: Listings and Search team, Completed

#233 fix: resolve auth issues caused by incorrect merge into main
  ThriftUni/app/(auth)/__tests__/ForgotPass.test.js
  ThriftUni/app/(auth)/__tests__/LoginScreen.test.js
  ThriftUni/app/(auth)/__tests__/Signup.test.js
  ThriftUni/app/(auth)/forgot.tsx
  ThriftUni/app/(auth)/index.tsx
  ThriftUni/app/(auth)/login.tsx
  ThriftUni/app/(auth)/signup.tsx
  ThriftUni/app/(tabs)/signup.tsx
  ThriftUni/app/login/signup.tsx
  ThriftUni/firebase/firebase.config.tsx
Labels: Milestone 3, Sign-up and Login Team, Completed

#288 Mutation testing stryker
  ThriftUni/app/(auth)/login.tsx
  ThriftUni/components/__tests__/login-test.tsx
  ThriftUni/package-lock.json
  ThriftUni/package.json
  ThriftUni/reports/mutation/mutation.html
  ThriftUni/stryker.conf.json
  ThriftUni/yarn.lock
Labels: documentation, Milestone 3, Pending Approval, Sign-up and Login Team, Completed

#303 BDD for wishlist
  ThriftUni/app/(tabs)/WishlistPage.tsx
  ThriftUni/components/features/thrift_wishlist_.feature
Labels: Milestone 3, Completed

#302 Add email verification to signup process
  ThriftUni/app/(auth)/signup.tsx
Labels: Milestone 3, Sign-up and Login Team, Completed

#227 User system username availibilty imp
  ThriftUni/app/(tabs)/Profile.tsx
  ThriftUni/app/(tabs)/settings.tsx
  ThriftUni/app/(tabs)/user_system.tsx
  ThriftUni/package-lock.json
  ThriftUni/package.json
  ThriftUni/yarn.lock
Labels: Pending Approval, Completed

#304 Mutation testing for main page
  ThriftUni/components/__tests__/ThriftUniApp.test.tsx
Labels: Milestone 3, Listings and Search team, Completed

#305 258 replace mock listings in my listings page
  ThriftUni/app/(tabs)/my_listings.tsx
  ThriftUni/backend/Api.ts
  ThriftUni/components/__tests__/DisplayMyListing.test.tsx
  ThriftUni/mock_backend/listingsData.json
  ThriftUni/mock_backend/mockApi.ts
Labels: Milestone 3, Listings and Search team, Completed

#314 Fixed merge conflict messages that should have been deleted and imports.
  ThriftUni/app/(auth)/forgot.tsx
  ThriftUni/app/(auth)/login.tsx
  ThriftUni/app/(auth)/signup.tsx
  ThriftUni/app/(tabs)/WishlistPage.tsx
  ThriftUni/app/(tabs)/signup.tsx
  ThriftUni/components/ListAnItem/ListItem.tsx
  ThriftUni/firebase/firebase.config.tsx
  ThriftUni/firebaseConfig.js
  ThriftUni/package-lock.json
  ThriftUni/package.json
  ThriftUni/yarn.lock
Labels: bug

#278 Added Tests for the SearchBar component of the general listings page and fixed some import bugs on the general listings page
  ThriftUni/app/(tabs)/index.tsx
  ThriftUni/components/ListingsPage/FilterMenu.tsx
  ThriftUni/components/ListingsPage/SearchBar.tsx
  ThriftUni/components/SellerCard.tsx
  ThriftUni/components/__tests__/FilterMenu-test.tsx
  ThriftUni/components/__tests__/SearchBar-test.tsx
Labels: Milestone 3, Pending Approval, Listings and Search team, TL Approved, Completed

#319 Updated main page so that the buttons work and changed test file
  ThriftUni/app/(tabs)/main_page.tsx
  ThriftUni/components/ListingDescription.tsx
  ThriftUni/components/__tests__/ThriftUniApp.test.tsx
  ThriftUni/yarn.lock
Labels: Milestone 3, Listings and Search team, Completed

#329 General Listings Integration, Tweaks and fixes for login and ListItems page and End to End Testing flows using Maestro
  ThriftUni/app/(auth)/login.tsx
  ThriftUni/app/(tabs)/ListItem.tsx
  ThriftUni/app/(tabs)/index.tsx
  ThriftUni/app/listings/[id].tsx
  ThriftUni/backend/Api.ts
  ThriftUni/components/ListAnItem/BrandInput.tsx
  ThriftUni/components/ListAnItem/Buttons.tsx
  ThriftUni/components/ListAnItem/PriceInput.tsx
  ThriftUni/components/ListAnItem/TitleInput.tsx
  ThriftUni/components/ListingDescription.tsx
  ThriftUni/components/ListingsPage/FilterMenu.tsx
  ThriftUni/components/ListingsPage/ProductCard.tsx
  ThriftUni/components/SellerCard.tsx
  ThriftUni/components/__tests__/CreateListingAndViewItFlow.yaml
  ThriftUni/firebase/InsertListing.tsx
Labels: Milestone 3, Pending Approval, Completed

#333 bdd wishlist testing
  ThriftUni/app/(tabs)/WishlistPage.tsx
  ThriftUni/components/__tests__/wishlist.steps.tsx
Labels: Milestone 3, Listings and Search team, Completed

#338 Display listing unit testing
  ThriftUni/components/ListingDescription.tsx
  ThriftUni/components/ProductImages.tsx
  ThriftUni/components/__tests__/DisplayIndividualListing-test.tsx
  ThriftUni/components/__tests__/ListingDescription-test.tsx
  ThriftUni/jest.config.js
  ThriftUni/yarn.lock
Labels: Listings and Search team

#340 Add Api Fuzzing Script
  ThriftUni/backend/Fuzz-Tests-Script.js
Labels: Completed

#341 Added mutation testing for DisplayIndividualListing component
  ThriftUni/components/DisplayIndividualListing.tsx
  ThriftUni/components/__tests__/DisplayIndividualListing-test.tsx
  ThriftUni/reports/DisplayIndividualListingMutation/index.html
  ThriftUni/yarn.lock
Labels: Listings and Search team

#346 Fix crash on Profile and PrivacyPage tabs
  ThriftUni/app/(tabs)/Profile.tsx
  ThriftUni/app/(tabs)/privacypage.tsx
  ThriftUni/components/ListingDescription.tsx
  ThriftUni/yarn.lock
Labels: bug, Milestone 3, Pending Approval, Completed

#320 Lecture topic tasks mutation testing for signup and forgot password feature
  ThriftUni/.gitignore
  ThriftUni/app/(auth)/__tests__/ForgotPass.test.js
  ThriftUni/app/(auth)/__tests__/Signup.test.js
  ThriftUni/app/(auth)/forgot.tsx
  ThriftUni/app/(auth)/signup.tsx
  ThriftUni/firebase/firebase.config.tsx
  ThriftUni/firebase/forgot.tsx
  ThriftUni/firebase/signup.tsx
Labels: Milestone 3, Sign-up and Login Team, Completed

#347 add property-tests for authentication
  ThriftUni/components/__tests__/__snapshots__/Wishlist.test.tsx.snap
  ThriftUni/firebase/__tests__/auth.fuzz.test.ts
  ThriftUni/firebase/__tests__/auth.property.test.ts
  ThriftUni/firebase/__tests__/fuzzHelpers.ts
  ThriftUni/firebase/signUp.tsx
  ThriftUni/jest.config.js
  ThriftUni/package.json
  ThriftUni/tsconfig.json
  ThriftUni/yarn.lock
Labels: documentation, Milestone 3, Sign-up and Login Team

#343 289 fix the the login and signup UI and resend email
  ThriftUni/app/(auth)/index.tsx
  ThriftUni/app/(auth)/login.tsx
  ThriftUni/app/(auth)/resend.tsx
  ThriftUni/app/(auth)/signup.tsx
  ThriftUni/app/(tabs)/signup.tsx
Labels: Milestone 3, Sign-up and Login Team, Completed

#356 Changed the current user reference to match the logged in user.
  ThriftUni/app/(tabs)/my_listings.tsx
  ThriftUni/backend/Api.ts
Labels: Milestone 3, Listings and Search team, Completed

#353 fixed bug
  ThriftUni/components/Wishlist/WishlistFilter.tsx
Labels: Listings and Search team, Completed
